"""agregar categoria e imagenes extra

Revision ID: e73d95886bd5
Revises: 
Create Date: 2026-06-24 16:22:27.591830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73d95886bd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url2', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('image_url3', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('categoria')
        batch_op.drop_column('image_url3')
        batch_op.drop_column('image_url2')

    # ### end Alembic commands ###
